<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relacionamento" nsURI="http://metamodelorelacionamento" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Raiz">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relacionamento" upperBound="-1"
        eType="#//Relacionamento" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relacionamento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obrigatorio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refFeature" eType="#//RefFeature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refConstrucaoMetamodeloMiddleware"
        upperBound="-1" eType="#//ReferenciaConstrucaoMetamodeloMiddleware" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" eType="ecore:EClass http://metamodelofeature#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalidadeMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalidadeMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenciaConstrucaoMetamodeloMiddleware">
    <eStructuralFeatures xsi:type="ecore:EReference" name="construcaoMetamodeloMiddleware"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalidadeMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalidadeMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
